INSERT INTO authors (name,email) VALUES
	 ('Jose Maria Requilme','requilme@gmail.com'),
	 ('Pablo Aimar','airma@gmail.com'),
	 ('Gilberto Silva','gilberto@gmail.com'),
	 ('juninho pernambucano','pecarbucano@gmail.com'),
	 ('Fabien Barthez','barthez@gmail.com');

INSERT INTO articles (title,body,user_id,creation_date) VALUES
	 ('Pierwszy artykul','Wszyscy mówili, że Kazimierz Górski był geniuszem, że to selekcjoner idealny, a to nieprawda. Selekcjonerem został w 1971 r., a rok wcześniej Górnik Zabrze grał w finale Pucharu Zdobywców Pucharów, gdzie 1:2 przegrał z Manchesterem City, a Legia Warszawa odpadła w półfinale Puchar Europy Mistrzów Klubowych z Feyenoordem Rotterdam. W związku z tym Kazio dostał na tacy piłkarzy klasy światowej i udało mu się tego nie zepsuć. Nawet wręcz przeciwnie, jeszcze bardziej ich połączył, skoro Włodzimierz Lubański był świadkiem na ślubie Kazimierza Deyny - wspomina Zarzeczny.',1,'2023-02-25 10:16:00'),
	 ('Drugi artykul','Z nim było jak z chodzeniem do pracy. Jak się ma kiepskiego szefa, to się nie chce. A jak chłop jest fajny, ciepły, otwarty, to przychodzisz pozytywnie nastawiony. I w takim nastroju piłkarze przyjeżdżali na zgrupowania do Kazia. On nie ingerował w drużynę. Obserwowałem jego pracę z bliska. Ci piłkarze sami sobie byli trenerami. Pozwalał im stworzyć własny mikroklimat do tego stopnia, że nawet nieistotne było dla nich - co rzadko jest przytaczane - że w słynnym meczu na Wembley w 1973 r. to Górski nie wytrzymał napięcia i uciekł do szatni na pięć minut przed jego końcem. Przewaga jednej drużyny nad drugą była tak wielka, jak jeszcze nigdy wcześniej w historii futbolu.',1,'2023-02-25 10:16:00'),
	 ('Trzeci artykul','W ogóle Kazio nie pracował za dużo. Lubił sobie posiedzieć na koniaczku w hotelu Victoria, i to z kumplami wszelkiej maści. W dzisiejszych czasach to nie do pomyślenia. Byłby głównym celem dla paparazzi. Śmiano się też, że on składy zapisywał na serwetkach, jedynym zresztą papierze, jaki w życiu widział, choć skończył studia. Czasami kelner nieopatrznie serwetkę zabierał i nagle cały skład mu uciekał. Akurat tego na mecz na Wembley nie zabrał. ',2,'2023-02-25 10:16:00'),
	 ('Czwarty artykul','Zwolnili go oczywiście za brak wyników, czyli za "tylko" drugie miejsce w igrzyskach olimpijskich w Montrealu. Że jak to, skoro miał takich piłkarzy jak Jan Tomaszewski, Grzegorz Lato, Kazimierz Deyna czy Andrzej Szarmach. Górski później mówił jednak o tej drużynie, że była "zatruta srebrem". Że im się w głowach popier… Jego największym atutem było to, że był normalnym gościem.',2,'2023-02-25 10:16:00'),
	 ('Piaty artykul','Po Górskim selekcjonerem został Jacek Gmoch, czyli człowiek, o którym napisałem pracę magisterską. Niewątpliwie megainteligentny gość, jedyny spośród naszych selekcjonerów, który jest inżynierem. Dostał najlepszych piłkarzy w dziejach Polski. Miał nie tylko wspaniałych ludzi z drużyny Górskiego, ale jeszcze młodych, jak Zbigniew Boniek czy Adam Nawałka. Jego problem polegał jednak na tym, że za wysoko zawiesił sobie poprzeczkę. Zapowiadał mistrzostwo świata w Argentynie, a zajął piąte miejsce. I wszyscy uznali to za porażkę. Zresztą po meczu otwarcia z mistrzami świata Niemcami, zremisowanym 0:0, ludzie byli wkurzeni. Dziś wyobraź sobie taką sytuację… ',3,'2023-02-25 10:16:00'),
	 ('Szosty artykul','Gmoch wiele razy mi opowiadał, że piłkarze sprzedali mecz Argentynie (0:2). Ponoć wiedział to od zawodnika, który grał w tym meczu i składał się na Polaków. Ile w tym prawdy, nie wiem, ale to był jego gwóźdź do trumny. Poza tym piłkarze go nie lubili. Z jednej strony - popisywał się przed nimi, a do tego powoływał graczy wykształconych. Dwóch było takich - Henryk Maculewicz i Bohdan Masztaler. I oni grali, bo Gmoch twierdził, że jak człowiek jest inteligentny do rozwiązywania jakichś tam zadań, to poradzi też sobie na boisku. Dziś by pewnie Messiego skreślił. Z drugiej strony - piłkarze nie wiedzieli czasem, co on do nich mówił, bo przecież to on wprowadził bank informacji i inne wykresy. ',3,'2023-02-25 10:16:00'),
('Siodmy artykul','Jako człowiek był jednak nieciekawy, o czym świadczy rzadko wspominana dziś sytuacja. Gmoch dzień przed meczem na Wembley, jako osoba bardzo przebiegła, zwolnił się z bycia asystentem Górskiego. Przypuszczam, tak samo zresztą myślał Kazio, że Gmoch postąpił w ten sposób, bo spodziewał się, że Polska przegra i nie awansuje na mundial. Potrzebny będzie wtedy nowy trener, więc do wzięcia będzie on. Przeliczył się.',3,'2023-02-25 10:16:00'),
 ('Osmy artykul','Mimo wszystko był świetnym trenerem, co zresztą potem potwierdził, pracując w Panathinaikosie Ateny i innych greckich klubach.
Po rezygnacji Gmocha selekcjonerem został jego asystent Ryszard Kulesza. To jedyny selekcjoner, którego pożegnałem w przytułku. Na jego przykładzie przekonałem się, jak cienka jest granica między wielkością a małością. Kiedyś był zawsze elegancki, uczciwy, w wypastowanych butach, a umarł w nędzy, biedzie i ubóstwie. Raz go odwiedziłem i poczułem się jak w "Locie nad kukułczym gniazdem". Widać było, jakie życie jest ulotne.',4,'2023-02-25 10:16:00');
